# NumPy Question practice

### Name- Nitesh Kumar

####  Batch-4

# Q1. Create a 5x5 array with random integers between 10 and 50.

In [1]:
import numpy as np

In [2]:
np.random.randint(10,50,(5,5))

array([[11, 10, 26, 44, 36],
       [24, 32, 11, 10, 15],
       [28, 31, 18, 49, 16],
       [18, 23, 49, 30, 34],
       [25, 34, 25, 14, 17]])

# Q2. Calculate the mean and standard deviation of each row in a 2D array.


In [21]:
arr=np.array([[1,2,3],[4,5,6]])

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr.ndim

2

In [24]:
mean_value=np.mean(arr,axis=1)

In [25]:
mean_value

array([2., 5.])

In [26]:
std_value=np.std(arr,axis=1)

In [27]:
std_value

array([0.81649658, 0.81649658])

# Q3. Normalize a 2D array by subtracting the mean and dividing by the standard deviation for each column.


In [28]:
arr # 2D array

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
normalized_arr=(arr-np.mean(arr,axis=0))/np.std(arr,axis=0)

In [30]:
normalized_arr

array([[-1., -1., -1.],
       [ 1.,  1.,  1.]])

# Q4. Generate a 2D Gaussian distribution with specified mean and covariance.


In [31]:
mean = [0, 0]

In [32]:
mean

[0, 0]

In [33]:
covariance = [[1, 0.5], [0.5, 2]]

In [34]:
covariance

[[1, 0.5], [0.5, 2]]

In [35]:
gaussian_array = np.random.multivariate_normal(mean, covariance, size=5)


In [36]:
gaussian_array

array([[ 0.00397841,  0.62754153],
       [-2.30149084,  0.53869034],
       [-0.39951948,  0.41420049],
       [ 1.34774157, -0.59610406],
       [-0.18828922, -2.33621464]])

# Q5. Implement matrix multiplication without using NumPy's dot function.


In [67]:
import numpy.matlib as nm

In [68]:
matrix1=nm.array([[1,2],[4,5]])
matrix2=nm.array([[5,6],[3,8]])

In [69]:
matrix1

array([[1, 2],
       [4, 5]])

In [71]:
 matrix2

array([[5, 6],
       [3, 8]])

In [72]:
matrix1@ matrix2

array([[11, 22],
       [35, 64]])

# Q6. Calculate the eigenvalues and eigenvectors of a given symmetric matrix.


In [78]:
arr=np.array([[0,3,8],[3,0,6],[8,6,0]])

In [79]:
arr

array([[0, 3, 8],
       [3, 0, 6],
       [8, 6, 0]])

In [80]:
arr.T

array([[0, 3, 8],
       [3, 0, 6],
       [8, 6, 0]])

In [81]:
eigenvalues, eigenvectors = np.linalg.eigh(arr)

In [82]:
eigenvalues

array([-8.71516889, -2.85590108, 11.57106997])

In [83]:
eigenvectors

array([[ 0.57977383,  0.57392511, -0.57833578],
       [ 0.31712994, -0.81278998, -0.48867274],
       [-0.75052708,  0.09991207, -0.6532432 ]])

# Q7. Compute the element-wise cosine of an array and find the maximum value.


In [84]:
arr

array([[0, 3, 8],
       [3, 0, 6],
       [8, 6, 0]])

In [86]:
cosine_arr=np.cos(arr)

In [87]:
cosine_arr

array([[ 1.        , -0.9899925 , -0.14550003],
       [-0.9899925 ,  1.        ,  0.96017029],
       [-0.14550003,  0.96017029,  1.        ]])

In [88]:
np.max(cosine_arr)

1.0

# Q8. Perform element-wise interpolation between two arrays.


In [95]:
import numpy as np

# Original arrays
x = np.array([0, 1, 2, 3, 4])
y = np.array([0, 2, 4, 6, 8])

# New x-coordinates for interpolation
new_x = np.array([0.5, 1.5, 2.5, 3.5])

In [96]:
# Interpolate corresponding elements between y1 arrays
interpolated_y = np.interp(new_x, x, y)

In [97]:
interpolated_y

array([1., 3., 5., 7.])

# Q9. Calculate the cumulative product of each column in a 2D array.


In [98]:
array=np.array([[1,2,3],[4,5,6]])

In [99]:
array.ndim

2

In [100]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
np.cumprod(array,axis=0)

array([[ 1,  2,  3],
       [ 4, 10, 18]])

# Q10. Create a random 2D array and find the kth smallest and largest elements.


In [116]:
arr3=np.random.randint(1,20,(3,3))

In [117]:
arr3

array([[ 8, 15, 13],
       [ 6, 15,  4],
       [ 9, 18,  9]])

In [118]:
arr3.ndim

2

In [119]:
# set k value
k=3

In [120]:
arr4=arr3.flatten()

In [121]:
arr4

array([ 8, 15, 13,  6, 15,  4,  9, 18,  9])

In [123]:
arr5=np.sort(arr4)

In [124]:
arr5

array([ 4,  6,  8,  9,  9, 13, 15, 15, 18])

In [139]:
arr5[k-1] # kth smallest number

8

In [140]:
arr5[-k] # kth largest number

15

# Q11. Implement the softmax function for a 1D array of values.


In [ ]:
# he softmax function takes an array of numbers and transforms them into a probability distribution where each value is
# between 0 and 1, and the sum of all values is equal to 1. 

In [1]:
import numpy as np

In [2]:
def softmax(x):
    exp_x=np.exp(x)
    softmax_value=exp_x/np.sum(exp_x)
    return softmax_value

In [5]:
x=np.array([1.0,2.0,3.0]) # input array

In [9]:
x.ndim # check dimension

1

In [6]:
np.exp(x) # exponential will amplyfy our input data

array([ 2.71828183,  7.3890561 , 20.08553692])

In [7]:
np.sum(np.exp(x)) # sum of all exponential element 

30.19287485057736

In [4]:
# call function
softmax(x)      # All element converted between 0 and 1 and their sum is approx equal to 1

array([0.09003057, 0.24472847, 0.66524096])

# Q12. Create a 2D array and replace all values below a certain threshold with a specified value.


In [10]:
# Take 2D input
x=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])

In [11]:
# check dimension of input
x.ndim

2

In [13]:
# define threshold and replacable value
threshold=4
replace_value=0

In [14]:
# replace value
x[x<threshold]=replace_value # It will check condition if True then replace with replace_value

In [15]:
x # updated input

array([[0, 0, 0],
       [4, 5, 6],
       [7, 8, 9]])

# Q13. Generate a random permutation of elements in an array.


In [17]:
import random

In [18]:
input_array=[1,2,3,4,5,6,7,8]

In [19]:
# create a copy of input array
permuted_array=input_array.copy()

In [20]:
random.shuffle(permuted_array)

In [21]:
# updated permuted_array
permuted_array

[5, 7, 1, 8, 3, 2, 6, 4]

# Q14. Create a 2D array and sort each row based on the values in a specific column.


In [23]:
input_array=np.array([[3,4,6],
             [5,8,3],
             [7,2,9]])

In [24]:
input_array.ndim

2

In [26]:
input_array

array([[3, 4, 6],
       [5, 8, 3],
       [7, 2, 9]])

In [29]:
sorted_data = [row for row in sorted(input_array, key=lambda x: x[2])]

In [32]:
sorted_data

[array([5, 8, 3]), array([3, 4, 6]), array([7, 2, 9])]

In [33]:
for row in sorted_data:
    print(row)

[5 8 3]
[3 4 6]
[7 2 9]


# Q15. Perform element-wise operations on arrays with different shapes, considering broadcasting rules.


In [38]:
# 1D array
arr=np.array([3,5,7])

In [39]:
arr

array([3, 5, 7])

In [40]:
arr+2

array([5, 7, 9])

In [41]:
# 2D array
arr1=np.array([[2,3,4],[8,4,3]])

In [42]:
arr1

array([[2, 3, 4],
       [8, 4, 3]])

In [44]:
arr1+arr

array([[ 5,  8, 11],
       [11,  9, 10]])

In [51]:
# new 1D array
arr3=np.array([2,5])

In [52]:
arr3.ndim

1

In [53]:
arr3

array([2, 5])

In [54]:
arr1+arr3

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [57]:
# we have to transpose the arr1 for compatble for broadcasting with arr3
arr1=arr1.T

In [58]:
arr1

array([[2, 8],
       [3, 4],
       [4, 3]])

In [59]:
arr1+arr3

array([[ 4, 13],
       [ 5,  9],
       [ 6,  8]])

# Q16. Reshape a 1D array into a 2D array with a specific number of rows and columns.


In [60]:
# 1D array
arr=np.array([2,4,6,7,8,3,7,4,1,9])

In [63]:
len(arr)

10

In [64]:
# convert into 2D with 5 row and 2 columns
arr.reshape(5,2)

array([[2, 4],
       [6, 7],
       [8, 3],
       [7, 4],
       [1, 9]])

# Q17. Calculate the mean squared error (MSE) between two arrays.


In [65]:
import numpy as np

In [74]:
predicted_values = np.array([1.7, 2.8, 3.9, 4.8])
actual_values = np.array([1.0, 2.0, 3.3, 5.2])

In [75]:
error=actual_values-predicted_values

In [76]:
# mean square error
mse=np.mean(error**2)

In [77]:
mse

0.41250000000000003

# Q18. Find the indices that would sort a 1D array.


In [78]:
# 1D array
arr=np.array([2,3,1,6,8])

In [79]:
np.argsort(arr) # get indices that sort a 1D array

array([2, 0, 1, 3, 4])

In [82]:
np.sort(arr)

array([1, 2, 3, 6, 8])

# Q19. Create a masked array by replacing all values below a threshold with NaN.


In [83]:
import numpy.ma as ma

In [92]:
# 1D array
arr=np.array([2,3,7,11,10,12,15,14],dtype=float)

In [93]:
# define threshold
threshold=10

In [94]:
mask_condition=arr<threshold

In [95]:
masked_array=ma.array(arr,mask=mask_condition,fill_value=np.nan)

In [96]:
masked_array

masked_array(data=[--, --, --, 11.0, 10.0, 12.0, 15.0, 14.0],
             mask=[ True,  True,  True, False, False, False, False, False],
       fill_value=nan)

# Q20. Calculate the Pearson correlation coefficient between two arrays.


In [97]:
# Define two arrays
arr1 = np.array([1,6,3,8,5])
arr2 = np.array([5,4,9,7,10])

In [98]:
# Calculate the Pearson correlation coefficient
correlation_matrix = np.corrcoef(arr1, arr2)

In [99]:
correlation_matrix

array([[1.        , 0.03629292],
       [0.03629292, 1.        ]])

In [100]:
pearson_coefficient = correlation_matrix[0, 1]


In [101]:
pearson_coefficient

0.036292919071221334

# Q21. Generate a 2D array of random integers and remove rows with duplicate elements.


In [112]:
import numpy as np

In [113]:
random_array=np.random.randint(0,11,(6,3))

In [114]:
random_array

array([[7, 8, 1],
       [5, 9, 8],
       [9, 4, 3],
       [0, 3, 5],
       [0, 2, 3],
       [8, 1, 3]])

In [115]:
np.unique(random_array,axis=0,return_index=True)

(array([[0, 2, 3],
        [0, 3, 5],
        [5, 9, 8],
        [7, 8, 1],
        [8, 1, 3],
        [9, 4, 3]]),
 array([4, 3, 1, 0, 5, 2]))

# Q22. Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal.

In [121]:
matrix=np.zeros((5,5))

In [122]:
matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [123]:
for i in range(1, 5):
    matrix[i, i - 1] = i

In [ ]:
# when i is 1, we set the element at (1, 0) to 1. When i is 2, we set the element at (2, 1) to 2, and so on.

In [124]:
matrix

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

# Q23. Given a NumPy array, replace all odd numbers with -1.

In [125]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [126]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
arr[arr%2!=0]=-1

In [130]:
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

# Q24. Given a 2D NumPy array, swap its rows - the first row becomes the last, the second becomes the second last, and so on.

In [133]:
arr=np.array([[8,2,4],[7,6,2],[4,6,9],[3,5,2],[1,4,2]])

In [134]:
arr

array([[8, 2, 4],
       [7, 6, 2],
       [4, 6, 9],
       [3, 5, 2],
       [1, 4, 2]])

In [135]:
arr[::-1]

array([[1, 4, 2],
       [3, 5, 2],
       [4, 6, 9],
       [7, 6, 2],
       [8, 2, 4]])

# Q25. Create a 2D NumPy array with dimensions 5x5 filled with random integers between 1 and 100, and then find the sum of each row and each column.

In [136]:
arr=np.random.randint(1,100,(5,5))

In [137]:
arr

array([[30, 20, 20, 15, 40],
       [33, 66, 10, 58, 33],
       [32, 75, 24, 36, 76],
       [56, 29, 35,  1,  1],
       [37, 54,  6, 39, 18]])

In [138]:
rows_sum=np.sum(arr,axis=1)
column_sum=np.sum(arr,axis=0)

In [139]:
rows_sum

array([125, 200, 243, 122, 154])

In [140]:
column_sum

array([188, 244,  95, 149, 168])

# Q26. Create a NumPy array with 20 random integers between -50 and 50. Replace all negative values with 0 without using a loop.

In [145]:
arr=np.random.randint(-50,50,20)

In [146]:
arr

array([-46,  -8,   8, -19, -49,  15,  -9,   7, -15, -39,  -4,  32,  41,
       -50, -36,  49,   3, -38,  -8,  34])

In [147]:
arr[arr<0]=0

In [148]:
arr

array([ 0,  0,  8,  0,  0, 15,  0,  7,  0,  0,  0, 32, 41,  0,  0, 49,  3,
        0,  0, 34])

# Q27. Create a NumPy array with 10 elements, and then add a border (filled with zeros) around it, making it a 3x3 matrix with the original array at its center.

In [188]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])

In [189]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [190]:
arr1=arr.reshape(5,2)

In [191]:
arr1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
# syntax of pad

In [ ]:
# numpy.pad(array, pad_width, mode='constant', constant_values=0)

pad_width: A tuple specifying how much padding to add along each axis. It is typically a tuple of tuples, where each inner tuple specifies the padding for one axis. For example, ((1, 1), (2, 2)) means add 1 element of padding before and after the first axis and 2 elements of padding before and after the second axis.

In [192]:
# Add a border of zeros to create a 3x3 matrix
bordered_matrix = np.pad(arr1, ((1, 1), (1, 1)), mode='constant', constant_values=0)

In [193]:
bordered_matrix

array([[ 0,  0,  0,  0],
       [ 0,  1,  2,  0],
       [ 0,  3,  4,  0],
       [ 0,  5,  6,  0],
       [ 0,  7,  8,  0],
       [ 0,  9, 10,  0],
       [ 0,  0,  0,  0]])

# Q28. Given two NumPy arrays, concatenate them horizontally (side by side) and vertically (stacked on top of each other).

In [205]:
array1=np.array([1, 2, 3])
array2=np.array([4, 5, 6])

In [206]:
Horizontal_concatenate=np.hstack((array1,array2))

In [207]:
Horizontal_concatenate

array([1, 2, 3, 4, 5, 6])

In [208]:
vertical_concatenate =np.vstack((array1,array2))

In [209]:
vertical_concatenate

array([[1, 2, 3],
       [4, 5, 6]])

# Q29. Given a 1D NumPy array of numbers, compute the element-wise absolute difference between each element and its mean.

In [210]:
arr=np.array([1,2,3,4,5,6,7])

In [211]:
arr1=np.mean(arr)

In [213]:
absolute_difference=np.abs(arr-arr1)

In [215]:
absolute_difference

array([3., 2., 1., 0., 1., 2., 3.])

# Q30. Generate a random 2D NumPy array of size 5x5 with values between 1 and 100. Find the indices of the top 5 maximum values in the array.

In [28]:
import numpy as np

In [29]:
np.random.seed(0)

In [30]:
arr=np.random.randint(1,100,(5,5))

In [31]:
arr

array([[45, 48, 65, 68, 68],
       [10, 84, 22, 37, 88],
       [71, 89, 89, 13, 59],
       [66, 40, 88, 47, 89],
       [82, 38, 26, 78, 73]])

In [35]:
indices_of_top_5_max = np.argpartition(arr.flatten(), -5)[-5:]

In [36]:
indices_of_top_5_max

array([17,  9, 11, 19, 12])

In [37]:
# Convert the flattened indices back to 2D indices
indices_of_top_5_max_2d = np.unravel_index(indices_of_top_5_max, arr.shape)

In [38]:
indices_of_top_5_max_2d

(array([3, 1, 2, 3, 2]), array([2, 4, 1, 4, 2]))